In [1]:
import pandas as pd
import numpy as np

In [3]:
sample_submission = pd.read_csv('./data/sample_submission.csv')
train = pd.read_csv('./data/train.csv')
test = pd.read_csv('./data/test.csv')

In [4]:
train.head(10)

,id,temperature,pressure,humidity,wind_speed,wind_direction,precipitation,snowing,cloudiness,target
0,TRAIN_00000,27.8816,1013.6,46.8,2.4,232.4,0.00,False,0.0,1.180
1,TRAIN_00001,5.7540,1026.6,76.6,3.6,172.0,0.00,False,8.8,8.581
2,TRAIN_00002,20.8220,1016.2,64.8,2.2,206.0,0.06,False,23.0,3.978
3,TRAIN_00003,20.0758,1017.4,72.6,0.8,215.4,0.00,False,0.0,8.301
4,TRAIN_00004,7.5260,1023.2,82.8,1.2,158.0,0.00,False,15.0,1.692
5,TRAIN_00005,24.8500,1011.2,64.6,2.2,126.0,0.00,False,0.0,1.971
6,TRAIN_00006,32.9420,1016.8,35.8,3.8,166.0,0.00,False,16.0,7.179
7,TRAIN_00007,14.8120,1006.8,73.0,4.0,172.0,0.12,False,60.0,9.110
8,TRAIN_00008,12.3210,1025.8,66.6,1.0,170.4,0.00,False,2.8,12.238
9,TRAIN_00009,20.7706,1004.4,67.0,1.4,215.2,0.00,False,11.2,7.333

In [6]:
train.shape

(19275, 10)

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19275 entries, 0 to 19274
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19275 non-null  object
 1   temperature     19275 non-null  float64
 2   pressure        19275 non-null  float64
 3   humidity        19275 non-null  float64
 4   wind_speed      19275 non-null  float64
 5   wind_direction  19275 non-null  float64
 6   precipitation   19275 non-null  float64
 7   snowing         19275 non-null  bool
 8   cloudiness      19275 non-null  float64
 9   target          19275 non-null  float64
dtypes: bool(1), float64(8), object(1)
memory usage: 1.3+ MB

In [11]:
train_X = train[train.columns[1:-1]]
train_y = train[train.columns[-1:]]

test_X = test[test.columns[1:-1]]

train_X.head(10)

,temperature,pressure,humidity,wind_speed,wind_direction,precipitation,snowing,cloudiness
0,27.8816,1013.6,46.8,2.4,232.4,0.00,False,0.0
1,5.7540,1026.6,76.6,3.6,172.0,0.00,False,8.8
2,20.8220,1016.2,64.8,2.2,206.0,0.06,False,23.0
3,20.0758,1017.4,72.6,0.8,215.4,0.00,False,0.0
4,7.5260,1023.2,82.8,1.2,158.0,0.00,False,15.0
5,24.8500,1011.2,64.6,2.2,126.0,0.00,False,0.0
6,32.9420,1016.8,35.8,3.8,166.0,0.00,False,16.0
7,14.8120,1006.8,73.0,4.0,172.0,0.12,False,60.0
8,12.3210,1025.8,66.6,1.0,170.4,0.00,False,2.8
9,20.7706,1004.4,67.0,1.4,215.2,0.00,False,11.2

In [33]:
train.isnull().sum()

id                0
temperature       0
pressure          0
humidity          0
wind_speed        0
wind_direction    0
precipitation     0
snowing           0
cloudiness        0
target            0
dtype: int64

In [36]:
train.corr()

,temperature,pressure,humidity,wind_speed,wind_direction,precipitation,snowing,cloudiness,target
temperature,1.000000,-0.018589,-0.674373,0.096674,-0.110825,-0.076996,-0.122623,-0.234963,-0.133893
pressure,-0.018589,1.000000,-0.004652,0.010000,0.026636,0.026427,-0.001803,0.020899,0.017871
humidity,-0.674373,-0.004652,1.000000,-0.337341,0.010250,0.109138,0.010607,0.338882,-0.040901
wind_speed,0.096674,0.010000,-0.337341,1.000000,0.360393,0.177916,0.060351,0.281130,0.330323
wind_direction,-0.110825,0.026636,0.010250,0.360393,1.000000,0.073662,0.057890,0.104410,0.191909
precipitation,-0.076996,0.026427,0.109138,0.177916,0.073662,1.000000,0.097696,0.340023,0.126229
snowing,-0.122623,-0.001803,0.010607,0.060351,0.057890,0.097696,1.000000,0.067269,-0.006278
cloudiness,-0.234963,0.020899,0.338882,0.281130,0.104410,0.340023,0.067269,1.000000,0.139371
target,-0.133893,0.017871,-0.040901,0.330323,0.191909,0.126229,-0.006278,0.139371,1.000000